### ISSUE TITLE
Missing log file results in failure

### ISSUE THREAD

**Issue by taftsanders** [JacobCallahan/apix#14]
```
apix explore --help
Traceback (most recent call last):
  File "/home/tasander/.local/bin/apix", line 11, in <module>
    load_entry_point('apix==0.3.1', 'console_scripts', 'apix')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/tasander/.local/lib/python3.8/site-packages/apix/__main__.py", line 10, in <module>
    from apix import logger
  File "/home/tasander/.local/lib/python3.8/site-packages/apix/logger.py", line 34, in <module>
    setup_logzero()
  File "/home/tasander/.local/lib/python3.8/site-packages/apix/logger.py", line 28, in setup_logzero
    logzero.logfile(
  File "/home/tasander/.local/lib/python3.8/site-packages/logzero/__init__.py", line 416, in logfile
    rotating_filehandler = RotatingFileHandler(filename, mode=mode, maxBytes=maxBytes, backupCount=backupCount, encoding=encoding)
  File "/usr/lib64/python3.8/logging/handlers.py", line 148, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib64/python3.8/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib64/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/logs/apix.log'
```
This only appears to be the issue with the `/tmp/logs` directory not being created. After creating, I get a clean run.
```
apix explore --help
usage: apix [-h] -n API_NAME -u HOST_URL [-b BASE_PATH] [-v VERSION] [-p PARSER] [--data-dir DATA_DIR] [--compact] [--debug]

optional arguments:
  -h, --help            show this help message and exit
  -n API_NAME, --api-name API_NAME
                        The name of the API (satellite6).
  -u HOST_URL, --host-url HOST_URL
                        The url for the API's host (http://my.host.domain/).
  -b BASE_PATH, --base-path BASE_PATH
                        The apidoc location relative to the host's url (apidoc/).
  -v VERSION, --version VERSION
                        The API version we're exploring (6.3).
  -p PARSER, --parser PARSER
                        The name of the parser to use when pulling data (apipie).
  --data-dir DATA_DIR   The base directory in which to save exports.
  --compact             Strip all the extra information from the saved data.
  --debug               Enable debug loggin level.
```

**Comment by JacobCallahan** [comment]
Interesting. Are you running apix from /tmp ?

**Comment by taftsanders** [comment]
> Interesting. Are you running apix from /tmp ?

Just so happens I was in /tmp when I produced this error:
`tasander at xbox in /tmp`

**Comment by JacobCallahan** [comment]
@Skyvar APIx is currently only able to be run from its base directory. There may be a push to allow a run-from-anywhere approach later, but not something I'm going to be implementing yet.
For now, just cd on back into the apix directory :)
